language: csharp
solution: src/MiracleDevs.CodeGen.sln
install:
  - nuget restore src/MiracleDevs.CodeGen.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/MiracleDevs.CodeGen.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Tests/MiracleDevs.CodeGen.Tests/bin/Release/MiracleDevs.CodeGen.Tests.dll