language: csharp
solution: src/MiracleDevs.CodeGen.sln
install:
  - nuget restore src/MiracleDevs.CodeGen.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/MiracleDevs.CodeGen.sln
  - cd testrunner/NUnit.ConsoleRunner.3.6.0/ 
  - ls
  - mono testrunner/NUnit.ConsoleRunner.3.6.0/nunit-console.exe src/Tests/MiracleDevs.CodeGen.Tests/bin/Release/MiracleDevs.CodeGen.Tests.dll